-- Atelier ALM — 0035 : bascule RLS des tables internes vers est_chef() (Vague 4, Etage 1).
-- Remplace 55 policies 'authenticated using(true)' + durcit 5 policies scoped (auth.uid) en
-- 'est_chef() AND ...'. Chef (claim app_role=equipe) : acces IDENTIQUE ; client (sans claim) : RIEN.
-- Applique apres preuve du claim sur jeton frais (invariant 1) + preuve de non-regression (invariant 2).
-- site_lecteur / site_ecrivain / RPC SECURITY DEFINER : INTOUCHES.

alter policy "equipe ecrit client" on public.client using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit client" on public.client using (public.est_chef());
alter policy "equipe ecrit composant" on public.composant using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit composant" on public.composant using (public.est_chef());
alter policy "equipe ecrit creneau_retrait" on public.creneau_retrait using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit creneau_retrait" on public.creneau_retrait using (public.est_chef());
alter policy "equipe ecrit demande_devis" on public.demande_devis using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit demande_devis" on public.demande_devis using (public.est_chef());
alter policy "equipe ecrit emplacement" on public.emplacement using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit emplacement" on public.emplacement using (public.est_chef());
alter policy "equipe ecrit famille_carte" on public.famille_carte using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit famille_carte" on public.famille_carte using (public.est_chef());
alter policy "equipe ecrit fulfillment_event" on public.fulfillment_event using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit fulfillment_event" on public.fulfillment_event using (public.est_chef());
alter policy "equipe ecrit horaire_boutique" on public.horaire_boutique using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit horaire_boutique" on public.horaire_boutique using (public.est_chef());
alter policy "equipe ecrit import_batch" on public.import_batch using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit import_batch" on public.import_batch using (public.est_chef());
alter policy "equipe ecrit import_mapping" on public.import_mapping using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit import_mapping" on public.import_mapping using (public.est_chef());
alter policy "equipe ecrit insight" on public.insight using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit insight" on public.insight using (public.est_chef());
alter policy "equipe ecrit lot" on public.lot using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit lot" on public.lot using (public.est_chef());
alter policy "equipe ecrit mouvement_stock" on public.mouvement_stock using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit mouvement_stock" on public.mouvement_stock using (public.est_chef());
alter policy "equipe ecrit newsletter_abonne" on public.newsletter_abonne using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit newsletter_abonne" on public.newsletter_abonne using (public.est_chef());
alter policy "equipe ecrit notification" on public.notification using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit notification" on public.notification using (public.est_chef());
alter policy "equipe ecrit parametre_rentabilite" on public.parametre_rentabilite using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit parametre_rentabilite" on public.parametre_rentabilite using (public.est_chef());
alter policy "equipe ecrit produit" on public.produit using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit produit" on public.produit using (public.est_chef());
alter policy "equipe lit profil" on public.profil using (public.est_chef());
alter policy "equipe ecrit reappro_ligne" on public.reappro_ligne using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit reappro_ligne" on public.reappro_ligne using (public.est_chef());
alter policy "equipe ecrit recette" on public.recette using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit recette" on public.recette using (public.est_chef());
alter policy "equipe ecrit recette_composant" on public.recette_composant using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit recette_composant" on public.recette_composant using (public.est_chef());
alter policy "equipe ecrit reglement" on public.reglement using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit reglement" on public.reglement using (public.est_chef());
alter policy "equipe ecrit releve_haccp" on public.releve_haccp using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit releve_haccp" on public.releve_haccp using (public.est_chef());
alter policy "equipe ecrit seuil_stock" on public.seuil_stock using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit seuil_stock" on public.seuil_stock using (public.est_chef());
alter policy "equipe ecrit social_post" on public.social_post using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit social_post" on public.social_post using (public.est_chef());
alter policy "equipe ecrit vente" on public.vente using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit vente" on public.vente using (public.est_chef());
alter policy "equipe ecrit vente_ligne" on public.vente_ligne using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit vente_ligne" on public.vente_ligne using (public.est_chef());
alter policy "equipe ecrit vente_ligne_composant" on public.vente_ligne_composant using (public.est_chef()) with check (public.est_chef());
alter policy "equipe lit vente_ligne_composant" on public.vente_ligne_composant using (public.est_chef());
alter policy "equipe gere son profil" on public.profil using (public.est_chef() and (auth.uid() = id)) with check (public.est_chef() and (auth.uid() = id));
alter policy "prefs notif lecture" on public.notification_preference using (public.est_chef() and (auth.uid() = profil_id));
alter policy "prefs notif ecriture" on public.notification_preference using (public.est_chef() and (auth.uid() = profil_id)) with check (public.est_chef() and (auth.uid() = profil_id));
alter policy "preference perso lecture" on public.user_preference using (public.est_chef() and (auth.uid() = profil_id));
alter policy "preference perso ecriture" on public.user_preference using (public.est_chef() and (auth.uid() = profil_id)) with check (public.est_chef() and (auth.uid() = profil_id));

-- Rollback (retour a l'etat d'avant, using(true) / scoped auth.uid) :
--
--   alter policy "equipe ecrit client" on public.client using (true) with check (true);
--   alter policy "equipe lit client" on public.client using (true);
--   alter policy "equipe ecrit composant" on public.composant using (true) with check (true);
--   alter policy "equipe lit composant" on public.composant using (true);
--   alter policy "equipe ecrit creneau_retrait" on public.creneau_retrait using (true) with check (true);
--   alter policy "equipe lit creneau_retrait" on public.creneau_retrait using (true);
--   alter policy "equipe ecrit demande_devis" on public.demande_devis using (true) with check (true);
--   alter policy "equipe lit demande_devis" on public.demande_devis using (true);
--   alter policy "equipe ecrit emplacement" on public.emplacement using (true) with check (true);
--   alter policy "equipe lit emplacement" on public.emplacement using (true);
--   alter policy "equipe ecrit famille_carte" on public.famille_carte using (true) with check (true);
--   alter policy "equipe lit famille_carte" on public.famille_carte using (true);
--   alter policy "equipe ecrit fulfillment_event" on public.fulfillment_event using (true) with check (true);
--   alter policy "equipe lit fulfillment_event" on public.fulfillment_event using (true);
--   alter policy "equipe ecrit horaire_boutique" on public.horaire_boutique using (true) with check (true);
--   alter policy "equipe lit horaire_boutique" on public.horaire_boutique using (true);
--   alter policy "equipe ecrit import_batch" on public.import_batch using (true) with check (true);
--   alter policy "equipe lit import_batch" on public.import_batch using (true);
--   alter policy "equipe ecrit import_mapping" on public.import_mapping using (true) with check (true);
--   alter policy "equipe lit import_mapping" on public.import_mapping using (true);
--   alter policy "equipe ecrit insight" on public.insight using (true) with check (true);
--   alter policy "equipe lit insight" on public.insight using (true);
--   alter policy "equipe ecrit lot" on public.lot using (true) with check (true);
--   alter policy "equipe lit lot" on public.lot using (true);
--   alter policy "equipe ecrit mouvement_stock" on public.mouvement_stock using (true) with check (true);
--   alter policy "equipe lit mouvement_stock" on public.mouvement_stock using (true);
--   alter policy "equipe ecrit newsletter_abonne" on public.newsletter_abonne using (true) with check (true);
--   alter policy "equipe lit newsletter_abonne" on public.newsletter_abonne using (true);
--   alter policy "equipe ecrit notification" on public.notification using (true) with check (true);
--   alter policy "equipe lit notification" on public.notification using (true);
--   alter policy "equipe ecrit parametre_rentabilite" on public.parametre_rentabilite using (true) with check (true);
--   alter policy "equipe lit parametre_rentabilite" on public.parametre_rentabilite using (true);
--   alter policy "equipe ecrit produit" on public.produit using (true) with check (true);
--   alter policy "equipe lit produit" on public.produit using (true);
--   alter policy "equipe lit profil" on public.profil using (true);
--   alter policy "equipe ecrit reappro_ligne" on public.reappro_ligne using (true) with check (true);
--   alter policy "equipe lit reappro_ligne" on public.reappro_ligne using (true);
--   alter policy "equipe ecrit recette" on public.recette using (true) with check (true);
--   alter policy "equipe lit recette" on public.recette using (true);
--   alter policy "equipe ecrit recette_composant" on public.recette_composant using (true) with check (true);
--   alter policy "equipe lit recette_composant" on public.recette_composant using (true);
--   alter policy "equipe ecrit reglement" on public.reglement using (true) with check (true);
--   alter policy "equipe lit reglement" on public.reglement using (true);
--   alter policy "equipe ecrit releve_haccp" on public.releve_haccp using (true) with check (true);
--   alter policy "equipe lit releve_haccp" on public.releve_haccp using (true);
--   alter policy "equipe ecrit seuil_stock" on public.seuil_stock using (true) with check (true);
--   alter policy "equipe lit seuil_stock" on public.seuil_stock using (true);
--   alter policy "equipe ecrit social_post" on public.social_post using (true) with check (true);
--   alter policy "equipe lit social_post" on public.social_post using (true);
--   alter policy "equipe ecrit vente" on public.vente using (true) with check (true);
--   alter policy "equipe lit vente" on public.vente using (true);
--   alter policy "equipe ecrit vente_ligne" on public.vente_ligne using (true) with check (true);
--   alter policy "equipe lit vente_ligne" on public.vente_ligne using (true);
--   alter policy "equipe ecrit vente_ligne_composant" on public.vente_ligne_composant using (true) with check (true);
--   alter policy "equipe lit vente_ligne_composant" on public.vente_ligne_composant using (true);
--   alter policy "equipe gere son profil" on public.profil using (auth.uid() = id) with check (auth.uid() = id);
--   alter policy "prefs notif lecture" on public.notification_preference using (auth.uid() = profil_id);
--   alter policy "prefs notif ecriture" on public.notification_preference using (auth.uid() = profil_id) with check (auth.uid() = profil_id);
--   alter policy "preference perso lecture" on public.user_preference using (auth.uid() = profil_id);
--   alter policy "preference perso ecriture" on public.user_preference using (auth.uid() = profil_id) with check (auth.uid() = profil_id);
